# Generated by Django 2.2.4 on 2019-08-22 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mascota',
            old_name='Persona',
            new_name='persona',
        ),
    ]
